#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 1
bspc config bottom_padding 2
bspc config left_padding 2
bspc config right_padding 2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AUTOSTART APPLICATIONS
sxhkd & 
compfy &
$HOME/startup/wallpaper.sh &
dunst &
polybar &
